# Generated by Django 5.1.3 on 2024-11-16 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tech_stack', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=100)),
                ('availabitlity', models.BooleanField(default=True)),
                ('goals', models.CharField(max_length=500)),
                ('Preferences', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
